name: Container CD

on:
    push:
        branches:
            - 'master'
        paths:
            - 'packages/server/**'

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: packages/server

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: 14.x

            - name: Build and push Docker images
              uses: docker/build-push-action@v1.1.0
              with:
                  path: packages/server
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}
                  repository: ryanchristian4427/freetunnel
                  tags: latest
